### ISSUE TITLE
The user will receive resource suggestions when she completes the Wayfinder questions

### ISSUE THREAD

**Issue by vlbee** [fac-13/GP_ProjectBernadette#12]
We did not discuss the User Journey if it's concluded that Bernadette is not a Kinship Carer after the two initial questions

Olivia - could you let us know your thoughts on this? Is there any alternative resources to direct clients towards?

**Comment by OliviaMervynSmith** [comment]
The other main reason she could be on our site is if she's a Grandparent looking for advice on general grandpareting/(non-Permanent) childcare, or if she has lost contact with her grandchildren - due to family breakdown, separation etc. This is some of the work we are also known for, and we have [pages/resources](https://www.grandparentsplus.org.uk/how-we-support-grandparents) on our website for these cases. Alternatively they could be a professional working with kinship carers who wants to know more about what we do, or simply an interested member of the public. This is why that initial question for the pop-up is so vital, and perhaps should go straight into 'are you raising a relative's child', so that it's clear the questions are for that demographic.

**Comment by tspeed90** [comment]
Thank you @OliviaMervynSmith for such a quick response! Very helpful!
